# RE6111068 黃子軒 HW1

## Part 2

In [1]:
import pandas as pd
import numpy as np

In [2]:
data1=pd.read_csv("data.csv")
crx=pd.read_csv("crx.csv")

In [3]:
data1

ID Diagnosis      3      4       5       6        7        8  \
0      842302         M  17.99  10.38  122.80  1001.0  0.11840  0.27760   
1      842517         M  20.57  17.77  132.90  1326.0  0.08474  0.07864   
2    84300903         M  19.69  21.25  130.00  1203.0  0.10960  0.15990   
3    84348301         M  11.42  20.38   77.58   386.1  0.14250  0.28390   
4    84358402         M  20.29  14.34  135.10  1297.0  0.10030  0.13280   
..        ...       ...    ...    ...     ...     ...      ...      ...   
564    926424         M  21.56  22.39  142.00  1479.0  0.11100  0.11590   
565    926682         M  20.13  28.25  131.20  1261.0  0.09780  0.10340   
566    926954         M  16.60  28.08  108.30   858.1  0.08455  0.10230   
567    927241         M  20.60  29.33  140.10  1265.0  0.11780  0.27700   
568     92751         B   7.76  24.54   47.92   181.0  0.05263  0.04362   

           9       10  ...      23     24      25      26       27       28  \
0    0.30010  0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560   
1    0.08690  0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660   
2    0.19740  0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450   
3    0.24140  0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630   
4    0.19800  0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500   
..       ...      ...  ...     ...    ...     ...     ...      ...      ...   
564  0.24390  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130   
565  0.14400  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220   
566  0.09251  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940   
567  0.35140  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810   
568  0.00000  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444   

         29      30      31  Unnamed: 31  
0    0.7119  0.2654  0.4601      0.11890  
1    0.2416  0.1860  0.2750      0.08902  
2    0.4504  0.2430  0.3613      0.08758  
3    0.6869  0.2575  0.6638      0.17300  
4    0.4000  0.1625  0.2364      0.07678  
..      ...     ...     ...          ...  
564  0.4107  0.2216  0.2060      0.07115  
565  0.3215  0.1628  0.2572      0.06637  
566  0.3403  0.1418  0.2218      0.07820  
567  0.9387  0.2650  0.4087      0.12400  
568  0.0000  0.0000  0.2871      0.07039  

[569 rows x 32 columns]

In [4]:
data1.replace("?",np.nan)
data1.dropna()

ID Diagnosis      3      4       5       6        7        8  \
0      842302         M  17.99  10.38  122.80  1001.0  0.11840  0.27760   
1      842517         M  20.57  17.77  132.90  1326.0  0.08474  0.07864   
2    84300903         M  19.69  21.25  130.00  1203.0  0.10960  0.15990   
3    84348301         M  11.42  20.38   77.58   386.1  0.14250  0.28390   
4    84358402         M  20.29  14.34  135.10  1297.0  0.10030  0.13280   
..        ...       ...    ...    ...     ...     ...      ...      ...   
564    926424         M  21.56  22.39  142.00  1479.0  0.11100  0.11590   
565    926682         M  20.13  28.25  131.20  1261.0  0.09780  0.10340   
566    926954         M  16.60  28.08  108.30   858.1  0.08455  0.10230   
567    927241         M  20.60  29.33  140.10  1265.0  0.11780  0.27700   
568     92751         B   7.76  24.54   47.92   181.0  0.05263  0.04362   

           9       10  ...      23     24      25      26       27       28  \
0    0.30010  0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560   
1    0.08690  0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660   
2    0.19740  0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450   
3    0.24140  0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630   
4    0.19800  0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500   
..       ...      ...  ...     ...    ...     ...     ...      ...      ...   
564  0.24390  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130   
565  0.14400  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220   
566  0.09251  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940   
567  0.35140  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810   
568  0.00000  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444   

         29      30      31  Unnamed: 31  
0    0.7119  0.2654  0.4601      0.11890  
1    0.2416  0.1860  0.2750      0.08902  
2    0.4504  0.2430  0.3613      0.08758  
3    0.6869  0.2575  0.6638      0.17300  
4    0.4000  0.1625  0.2364      0.07678  
..      ...     ...     ...          ...  
564  0.4107  0.2216  0.2060      0.07115  
565  0.3215  0.1628  0.2572      0.06637  
566  0.3403  0.1418  0.2218      0.07820  
567  0.9387  0.2650  0.4087      0.12400  
568  0.0000  0.0000  0.2871      0.07039  

[569 rows x 32 columns]

In [5]:
label1=data1["Diagnosis"]
data1=data1.drop(columns=['Diagnosis','ID'])

In [6]:
for i in range(0,len(label1)):
    if(label1[i]=='M'):
        label1[i]=1
    else:
        label1[i]=-1

C:\Users\andre\AppData\Local\Temp\ipykernel_19464\2993124554.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label1[i]=1
C:\Users\andre\AppData\Local\Temp\ipykernel_19464\2993124554.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label1[i]=-1


In [7]:
label_ori=label1
data1=(data1-data1.mean())/data1.std()
data1['beta_0']=[1]*len(data1)
data_ori=data1

In [8]:
import random
def shuffle(df,label):
    temp=list(range(len(df)))
    random.shuffle(temp)
    df=df.iloc[temp,:]
    label=label[temp]
    return(df,label)

In [9]:
random.seed(6111016)
data1,label1=shuffle(data1,label1)

## Part 2

In [10]:
def updating_rule(beta,row,label):
    judge=0
    count=0
    while judge==0 and count <10:
        score=0
        for i in range(0,len(beta)):
            score=score+beta[i]*row[i]
        if (score>=0 and label==1):
            judge=1
        if (score<0 and label==-1):
            judge=1
        if (score>=0 and label==-1):
            for i in range(0,len(beta)):
                if i == (len(beta)-1):
                    if row[i]>=0:
                        beta[i]=beta[i]-30
                    else:
                        beta[i]=beta[i]+30
                else:
                    if row[i]>=0:
                        beta[i]=beta[i]-1
                    else:
                        beta[i]=beta[i]+1
        if (score<0 and label==1):
            for i in range(0,len(beta)):
                if i == (len(beta)-1):
                    if row[i]>=0:
                        beta[i]=beta[i]+30
                    else:
                        beta[i]=beta[i]-30
                else:
                    if row[i]>=0:
                        beta[i]=beta[i]+1
                    else:
                        beta[i]=beta[i]-1
        count=count+1
    return beta

In [11]:
beta=[0]*31

In [12]:
for i in range(0,len(label1)):
    beta=updating_rule(beta,data1.iloc[i],label1[i])

In [13]:
def predict_value(beta,row):
    score=0
    for i in range(0,len(beta)):
        score=score+beta[i]*row[i]
        if (score>=0):
            judge=1
        if (score<0):
            judge=-1
    return judge

In [14]:
label_pred=[]
for i in range(0,len(label1)):
    label_pred.append(predict_value(beta,data1.iloc[i]))

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(label_pred,list(label1))

array([[316,  20],
       [ 41, 192]], dtype=int64)

## Part 3

### For hat(beta) = Inv(t(X)X)t(X)Y , we need to add beta_0 into the matrix

In [16]:
normalized_df=data1

In [17]:
np_normalized_df=normalized_df.to_numpy()

In [18]:
np_normalized_df

array([[-0.30569717,  0.00473177, -0.38516156, ..., -0.74636272,
        -1.16579954,  1.        ],
       [-0.45041707, -0.28357088, -0.51644278, ..., -1.07933254,
        -1.59101887,  1.        ],
       [ 1.8111861 ,  1.98099992,  1.74620354, ..., -0.74959543,
        -0.03686437,  1.        ],
       ...,
       [ 1.74024497,  0.86963971,  1.66389556, ...,  1.27408527,
        -0.01471753,  1.        ],
       [ 0.53992108, -0.87877635,  0.56919945, ...,  0.19112515,
         0.40385775,  1.        ],
       [-1.24552523, -1.70183391, -1.2646223 , ...,  0.33013197,
        -0.13486414,  1.        ]])

In [19]:
t_np_df=np_normalized_df.transpose(1,0)

In [20]:
from numpy.linalg import inv
def least_squares(df,label):
    temp_df=np.matmul(df.transpose(1,0),df)
    temp_inv=inv(np.matrix(temp_df))
    output_df=np.matmul(temp_inv,df.transpose(1,0))
    output_df=np.matmul(output_df,label)
    return output_df

In [21]:
least_beta=least_squares(np_normalized_df,label1)
least_beta

array([-1.534878713845798, 0.03910044670157291, 1.1537088631169394,
       0.2237010786801092, 0.002382157751795744, -0.4459546514521419,
       0.22289615199083995, 0.16621842932205455, 0.005631397817998768,
       0.00046967806109653523, 0.241237636592737, -0.0074566007967997085,
       -0.09106537111784656, -0.08399621989566915, 0.09520576506739739,
       0.0023246037734371036, -0.21525486338806799, 0.1304145465490944,
       0.028061697579600805, -0.03781997562456793, 1.8867343561258716,
       0.0880067287864253, -0.16364777943606534, -1.1514941345144694,
       0.02478948192497116, 0.021132900396142074, 0.15905148593371546,
       0.061040352929052695, 0.06889407085610272, 0.15545271731769975,
       -0.25483304042179145], dtype=object)

In [22]:
label_pred_least=[]
for i in range(0,len(label1)):
    label_pred_least.append(predict_value(least_beta,normalized_df.iloc[i]))

In [23]:
confusion_matrix(label_pred_least,list(label1))

array([[355,  18],
       [  2, 194]], dtype=int64)

### Part 4

In [24]:
def vote_perceptron(df,label):
    iter_i=1
    random.seed(iter_i*6111016)
    label_total=[]
    while iter_i<=25:
        shuf_df,shuf_label=shuffle(df,label)
        beta=[0]*31
        for i in range(0,len(shuf_label)):
            beta=updating_rule(beta,shuf_df.iloc[i],shuf_label[i])
        label_pred=[]
        for i in range(0,len(label)):
            label_pred.append(predict_value(beta,df.iloc[i]))
        label_total.append(label_pred)
        iter_i=iter_i+1
    label_total=pd.DataFrame(label_total)
    mean_label=label_total.mean()
    out_label=[]
    for i in range(0,len(mean_label)):
        if(mean_label[i]>=0):
            out_label.append(1)
        else:
            out_label.append(-1)
    return out_label

In [25]:
vote_pred=vote_perceptron(data_ori,label_ori)

In [26]:
confusion_matrix(vote_pred,list(label_ori))

array([[274, 134],
       [ 83,  78]], dtype=int64)

In [27]:
def average_perceptron(df,label):
    iter_i=1
    random.seed(iter_i*6111016)
    beta_total=[]
    while iter_i<=25:
        shuf_df,shuf_label=shuffle(df,label)
        beta=[0]*31
        for i in range(0,len(shuf_label)):
            beta=updating_rule(beta,shuf_df.iloc[i],shuf_label[i])
        beta_total.append(beta)
        iter_i=iter_i+1
    beta_total=pd.DataFrame(beta_total)
    mean_beta=beta_total.mean()
    out_label=[]
    for i in range(0,len(label)):
        out_label.append(predict_value(mean_beta,df.iloc[i]))
    return out_label

In [28]:
average_pred=average_perceptron(data_ori,label_ori)

In [29]:
confusion_matrix(average_pred,list(label_ori))

array([[280, 121],
       [ 77,  91]], dtype=int64)

### Part 5

In [30]:
ini_beta=[0]*31
ini_beta[30]=sum(label_ori)
random.seed(6111016)
ini_beta[random.randint(0,29)]=1

In [31]:
def minimize_linear_classifier(beta,df,label):
    random.seed(999)
    shuf_df,shuf_label=shuffle(df,label)
    dis_ori=np.array(shuf_df).dot(np.array(beta))
    dis_ori=np.absolute(dis_ori)
    dis_ori_sum=sum(dis_ori)/((np.array(beta).dot(np.array(beta)))**0.5)
    for k in range(0,40):
        for i in range(0,len(shuf_df)):
            score=0
            temp_beta=beta
            for j in range(0,len(beta)):
                score=score+beta[j]*shuf_df.iloc[i][j]
            if (score>=0 and shuf_label[i]==-1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-30
                        else:
                            temp_beta[g]=temp_beta[g]+30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1
                        else:
                            temp_beta[g]=temp_beta[g]+1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
            if (score<0 and shuf_label[i]==1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+30
                        else:
                            temp_beta[g]=temp_beta[g]-30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1
                        else:
                            temp_beta[g]=temp_beta[g]-1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
    return beta

In [32]:
mini_beta = minimize_linear_classifier(ini_beta,data_ori,label_ori)

In [33]:
label_pred_mini=[]
for i in range(0,len(label1)):
    label_pred_mini.append(predict_value(mini_beta,data1.iloc[i]))
confusion_matrix(label_pred_mini,list(label1))

array([[267,  11],
       [ 90, 201]], dtype=int64)

### Part 6

In [34]:
def slack_minimize_linear_classifier(slack_C,beta,df,label):
    random.seed(9999999)
    shuf_df,shuf_label=shuffle(df,label)
    dis_ori=np.array(shuf_df).dot(np.array(beta))
    dis_ori=np.absolute(dis_ori)
    dis_ori_sum=0
    for i in range(0,len(dis_ori)):
        if (dis_ori[i])>slack_C:
            dis_ori_sum=dis_ori_sum+dis_ori[i]
    dis_ori_sum=dis_ori_sum/((np.array(beta).dot(np.array(beta)))**0.5)
    for k in range(0,40):
        for i in range(0,len(shuf_df)):
            score=0
            temp_beta=beta
            for j in range(0,len(beta)):
                score=score+beta[j]*shuf_df.iloc[i][j]
            if (score>=0 and shuf_label[i]==-1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-30
                        else:
                            temp_beta[g]=temp_beta[g]+30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]-1
                        else:
                            temp_beta[g]=temp_beta[g]+1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=sum(dis_temp)/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
            if (score<0 and shuf_label[i]==1):
                for g in range(0,len(beta)):
                    if g == (len(beta)-1):
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+30
                        else:
                            temp_beta[g]=temp_beta[g]-30
                    else:
                        if shuf_df.iloc[i][j]>=0:
                            temp_beta[g]=temp_beta[g]+1
                        else:
                            temp_beta[g]=temp_beta[g]-1
                    dis_temp=np.array(shuf_df).dot(np.array(temp_beta))
                    dis_temp=np.absolute(dis_temp)
                    dis_temp_sum=0
                    for h in range(0,len(dis_temp)):
                        if(dis_temp[h]>slack_C):
                            dis_temp_sum=dis_temp_sum+dis_temp[h]
                    dis_temp_sum=dis_temp_sum/((np.array(temp_beta).dot(np.array(temp_beta)))**0.5)
                    if(dis_temp_sum<=dis_ori_sum):
                        beta=temp_beta
    return beta

In [35]:
slack_beta=slack_minimize_linear_classifier(100,ini_beta,data_ori,label_ori)
label_pred_slack=[]
for i in range(0,len(label1)):
    label_pred_slack.append(predict_value(slack_beta,data1.iloc[i]))
confusion_matrix(label_pred_slack,list(label1))

array([[311,  22],
       [ 46, 190]], dtype=int64)

### Part 7

In [36]:
from sklearn.svm import SVC
model = SVC()
model.fit(data_ori,np.array(label_ori,dtype=int))
predictions = model.predict(data_ori)
confusion_matrix(predictions,np.array(label_ori,dtype=int))

array([[357,   7],
       [  0, 205]], dtype=int64)

In [37]:
label_ori

0       1
1       1
2       1
3       1
4       1
       ..
564     1
565     1
566     1
567     1
568    -1
Name: Diagnosis, Length: 569, dtype: object